import { graphql } from '../gql'; // Adjusted path assuming hooks are in src/hooks and gql is in src/gql
import { BudgetBalance } from '../gql/graphql'; // Will be generated by codegen
import { useQuery, UseQueryArgs } from 'urql';

// Define the GraphQL query for fetching budgets
// The actual DocumentNode will be generated by graphql-codegen
const GetBudgetsQueryDocument = graphql(`
  query GetBudgets($year: Int!) {
    budgets(year: $year) {
      accountId
      accountCode
      accountName
      planned
      actual
      remaining
      ratio
    }
  }
`);

// Custom hook to fetch budgets
export const useGetBudgets = (year: number | undefined) => {

  const [{data, fetching, error}, refetchBudgets] = useQuery({
    query: GetBudgetsQueryDocument,
    variables: { year: year! },
    pause: !year,
  });

  return {
    loading: fetching,
    error: error,
    budgets: data?.budgets,
    refetchBudgets,
  };
}; 