import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GraphQLProvider } from '@/providers/UrqlProvider';
import { Toaster } from 'react-hot-toast'; // Added Toaster import

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <GraphQLProvider>
          {children}
          <Toaster /> {/* Added Toaster component here */}
        </GraphQLProvider>
      </body>
    </html>
  );
}